### ISSUE TITLE
Tabswitch in multiple windows

### ISSUE THREAD

**Issue by hu-ry** [FlorianSchroevers/tabswitch#1]
Tabswitch currently only works in one firefox windows instance.
I don't know if you're already aware of this, but being able to switch tabs on the window which is currently in focus would be nice.

Otherwise this simple add-on is a game changer for me!

-hury

**Comment by FlorianSchroevers** [comment]
Hey there, 

Thanks for the feedback! Currently I'm a bit busy but I will look into it eventually. In the meantime you are more than welcome to give it a go!

-Florian
